-- CreateEnum
CREATE TYPE "AuditAction" AS ENUM ('USER_REGISTERED', 'USER_LOGGED_IN', 'USER_LOGGED_OUT', 'REFRESH_TOKEN_CREATED', 'REFRESH_TOKEN_REVOKED', 'EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_DELETED', 'BOOKING_CREATED', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'BOOKING_EXPIRED', 'BOOKING_HOLD_CREATED', 'BOOKING_HOLD_RELEASED', 'PAYMENT_STARTED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'FRAUD_DETECTED', 'PURCHASE_LIMIT_EXCEEDED', 'DUPLICATE_REQUEST_BLOCKED', 'WORKER_RELEASE_EXPIRED_BOOKING');

-- CreateEnum
CREATE TYPE "EntityType" AS ENUM ('BOOKING', 'EVENT');

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" SERIAL NOT NULL,
    "action" "AuditAction" NOT NULL,
    "userId" INTEGER NOT NULL,
    "entityType" TEXT,
    "entityId" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
